### PR TITLE
Vs2015 integration

### PR DESCRIPTION
**Pull request by dbc60**
Created a VS2015 solution and project file. Build the debug/release static libs as `lib_jsond.lib` and `lib_json.lib`, respectively and use a post-build event to copy them to `./lib/`.

### CODE REVIEW

**Comment by yankeehacker** [comment]
I assume this is for the sensors, as the CnC repository just uses the `amalgamate.py` script. We eventually want to standardize our library usage, although not a requirement for this commit. 

Why do we rename `jsoncpp` to `lib_json.lib`?

**Comment by dbc60** [comment]
This is for making a submodule in tsEventQuery.

I'm not sure I renamed jsoncpp to lib_json.lib. All I did was copy the original msvc2010 solution and project files to a different directoryand use the IDE to update them to msvc2015. I also added a post build step to copy the debug and release versions, but that's technically not necessary. the tsEventQuery project can link to the correct libs directly.

**Comment by yankeehacker** [comment]
Sounds legit. LGTM.

**Comment by michaelchen16** [comment]
LGTM!

**Pull request merged**
